import { ArrowDownIcon, ArrowUpRightIcon, GitHubIcon, LinkedInIcon } from "@/components/icons";
import { OperationsModel, OpportunityCalculator, CopyEmail } from "@/components/operations-interactive";
import { operationsCopy } from "@/lib/operations";
import { education, experience, languages, siteConfig, socials, t } from "@/lib/site";
import type { Locale } from "@/i18n/config";

function SectionIntro({ label, title, text }: { label: string; title: string; text?: string }) {
  return <div className="ops-section-intro"><p className="ops-eyebrow">{label}</p><div><h2>{title}</h2>{text && <p>{text}</p>}</div></div>;
}

function ProjectArt({ type, locale }: { type: string; locale: Locale }) {
  const es = locale === "es";
  if (type === "querybay") return <div className="project-art querybay-art" aria-hidden="true"><div className="art-grid" /><span className="art-corner">CONVERSATION / KNOWLEDGE / ACTION</span><div className="chat-window"><div className="chat-title"><span className="querybay-symbol">q.</span><div>QueryBay<small>{es ? "Asistente de negocio" : "Business assistant"}</small></div><i /></div><div className="chat-bubble incoming">{es ? "¿Podemos conectar atención y operaciones?" : "Can we connect support and operations?"}</div><div className="chat-context"><span>↳</span> {es ? "Conocimiento del negocio" : "Business knowledge"}<b>RAG</b></div><div className="chat-bubble outgoing">{es ? "Una conversación. Todo el contexto. El siguiente paso, conectado." : "One conversation. All the context. The next step, connected."}</div><div className="chat-bottom"><span>LLM</span><i /><span>API</span><i /><span>{es ? "EQUIPO" : "TEAM"}</span></div></div><span className="art-caption">{es ? "Esquema conceptual del flujo" : "Conceptual workflow illustration"}</span></div>;
  if (type === "data") return <div className="project-art data-art" aria-hidden="true"><span className="art-corner">DATA / CONNECT / ACT</span><div className="data-lines">{["SOURCE_01", "SOURCE_02", "SOURCE_03"].map((label, i) => <div key={label}><span>{label}</span><div>{Array.from({ length: 7 }, (_, j) => <i key={j} style={{ opacity: ((i + j) % 3 + 1) / 3 }} />)}</div></div>)}</div><div className="data-pipeline"><span>↳</span><strong>{es ? "Unificar. Validar. Activar." : "Unify. Validate. Activate."}</strong><span>↗</span></div><span className="art-caption">{es ? "Arquitectura conceptual" : "Conceptual architecture"}</span></div>;
  return <div className="project-art industrial-art" aria-hidden="true"><span className="art-corner">INVENTORY / PEOPLE / PROCESS</span><svg className="warehouse-art" viewBox="0 0 440 220"><g fill="none" stroke="currentColor" strokeWidth="1.2">{[0, 1, 2, 3, 4].map((i) => <g key={i} transform={`translate(${50 + i * 63} ${88 - (i % 2) * 32})`}><path d="M0 0l29-17 29 17v51L29 68 0 51z M0 0l29 17L58 0 M29 17v51 M7 16l15 8v26L7 42z M36 26l15-8v27l-15 8z" /><path d="M0-5l29-17L58-5" opacity=".4" /></g>)}<path d="M30 160l174 46 205-57 M204 206v-24" strokeDasharray="4 5" /></g></svg><div className="warehouse-label"><strong>05</strong><span>{es ? "almacenes\nuna operación" : "warehouses\none operation"}</span></div><span className="art-caption">{es ? "Experiencia en gestión operativa" : "Operations management experience"}</span></div>;
}

export function OperationsPortfolio({ locale }: { locale: Locale }) {
  const c = operationsCopy[locale];
  return <div className="ops-portfolio">
    <section className="ops-hero ops-container" aria-labelledby="hero-title">
      <div className="hero-meta"><span className="ops-eyebrow">{c.eyebrow}</span><span className="hero-edition">PORTFOLIO / {new Date().getFullYear()}</span></div>
      <div className="hero-layout"><div className="hero-copy"><div className="hero-person"><span className="person-line" />JEAN CARRASCO</div><h1 id="hero-title">{c.headline.map((line, i) => <span key={line} className={i === 2 ? "hero-accent" : undefined}>{line}</span>)}</h1><p className="hero-description">{c.intro}</p><div className="hero-actions"><a href="#contact" className="ops-button ops-button-primary">{c.primary}<ArrowUpRightIcon width={18} /></a><a href="#work" className="ops-text-link">{c.secondary}<ArrowDownIcon width={16} /></a></div>{siteConfig.available && <p className="hero-availability"><span className="status-dot" />{c.available}</p>}</div><OperationsModel copy={c} /></div>
      <div className="hero-bottom"><span>01 / 05</span><p>{c.aboutNote}</p><a href="#about" aria-label={locale === "es" ? "Explorar enfoque" : "Explore the approach"}><ArrowDownIcon width={18} /></a></div>
    </section>
    <div className="discipline-strip"><div className="ops-container">{c.strip.map((item, i) => <span key={item}><i aria-hidden="true">{["✳", "+", "↗", "◈"][i]}</i>{item}</span>)}</div></div>
    <section id="about" className="ops-container ops-section"><SectionIntro label={c.aboutLabel} title={c.aboutTitle} text={c.aboutText} /><div className="ops-metrics">{["60", "05", "02"].map((value, i) => <div key={value}><strong>{value}<span>{i === 0 ? "↗" : "/"}</span></strong><p>{c.metrics[i]}</p></div>)}</div></section>
    <section id="skills" className="ops-container ops-section capabilities-section"><SectionIntro label={c.capabilitiesLabel} title={c.capabilitiesTitle} text={c.capabilitiesIntro} /><div className="capabilities-grid">{c.capabilities.map((item, i) => <article key={item.mark}><div className="capability-top"><span>{item.mark}</span><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">{i === 0 ? <><path d="M6 13h36M6 24h36M6 35h36" /><circle cx="16" cy="13" r="4" /><circle cx="32" cy="24" r="4" /><circle cx="22" cy="35" r="4" /></> : i === 1 ? <><rect x="4" y="5" width="14" height="14" rx="2" /><rect x="30" y="29" width="14" height="14" rx="2" /><path d="M18 12h19v17M11 19v17h19" /></> : <><path d="M24 4l6 13 14 7-14 6-6 14-6-14-14-6 14-7z" /><path d="M24 16v16M16 24h16" /></>}</svg></div><h3>{item.title}</h3><p>{item.text}</p><ul className="ops-tags">{item.tags.map(tag => <li key={tag}>{tag}</li>)}</ul></article>)}</div></section>
    <section id="work" className="work-section"><div className="ops-container ops-section"><SectionIntro label={c.workLabel} title={c.workTitle} text={c.workIntro} /><div className="case-grid">{c.cases.map((project, i) => <article className={`case-card case-${project.type}`} key={project.type}><ProjectArt type={project.type} locale={locale} /><div className="case-content"><p className="ops-eyebrow">{project.category}</p><div className="case-name"><span>{project.name}</span><span>0{i + 1}</span></div><h3>{project.title}</h3><p>{project.text}</p><ul className="ops-tags">{project.tags.map(tag => <li key={tag}>{tag}</li>)}</ul><details className="case-details"><summary>{c.detail}<span aria-hidden="true">+</span></summary><div>{[[c.challenge, project.challenge], [c.approach, project.approach], [c.measurement, project.measure]].map(([title, text]) => <div key={title}><h4>{title}</h4><p>{text}</p></div>)}{i === 0 && <a href="https://querybay.com" target="_blank" rel="noopener noreferrer" className="ops-text-link">{c.visit}<ArrowUpRightIcon width={16} /></a>}</div></details></div></article>)}</div></div></section>
    <section id="method" className="ops-container ops-section"><SectionIntro label={c.methodLabel} title={c.methodTitle} /><div className="method-grid">{c.steps.map((step, i) => <article key={step.title}><div className="method-number"><span>0{i + 1}</span><i aria-hidden="true">↗</i></div><h3>{step.title}</h3><p>{step.text}</p><span className="method-deliverable">{step.deliverable}</span></article>)}</div></section>
    <section id="opportunity" className="calculator-section"><div className="ops-container ops-section"><SectionIntro label={c.calculatorLabel} title={c.calculatorTitle} text={c.calculatorText} /><OpportunityCalculator copy={c} locale={locale} /><p className="calculator-caveat">{c.caveat}</p></div></section>
    <section id="experience" className="ops-container ops-section"><SectionIntro label={c.experienceLabel} title={c.experienceTitle} /><div className="experience-list">{experience.map((job, i) => <article key={job.company}><span className="experience-index">0{i + 1}</span><div><h3>{job.company}</h3><p className="experience-role">{t(job.role, locale)}</p><p className="experience-description">{t(job.description, locale)}</p></div><div className="experience-meta"><span>{t(job.period, locale)}</span><span>{job.location}</span></div></article>)}</div><div className="credentials"><div><p className="ops-eyebrow">{c.education}</p>{education.map(item => <div className="credential" key={item.school}><h3>{t(item.degree, locale)}</h3><p>{item.school}</p><span>{t(item.period, locale)}</span></div>)}</div><div><p className="ops-eyebrow">{c.languages}</p>{languages.map(item => <div className="language-row" key={item.name.en}><span>{t(item.name, locale)}</span><span>{t(item.level, locale)}</span></div>)}</div></div></section>
    <section id="contact" className="ops-contact"><div className="ops-container"><p className="ops-eyebrow">{c.contactLabel}</p><div className="contact-layout"><div><h2>{c.contactTitle}</h2><p>{c.contactText}</p><a href={`mailto:${siteConfig.email}`} className="ops-button ops-button-primary">{c.contactCta}<ArrowUpRightIcon width={20} /></a></div><div className="contact-aside"><div className="contact-monogram" aria-hidden="true">JC<span>↗</span></div><a className="contact-email" href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a><CopyEmail copy={c} /><div className="contact-socials"><a href={socials.linkedin} target="_blank" rel="noopener noreferrer"><LinkedInIcon width={16} />LinkedIn<ArrowUpRightIcon width={14} /></a><a href={socials.github} target="_blank" rel="noopener noreferrer"><GitHubIcon width={16} />GitHub<ArrowUpRightIcon width={14} /></a></div></div></div><div className="contact-bottom"><span><span className="status-dot" />{c.contactOptions}</span><span>INDUSTRY + TECHNOLOGY + AI</span></div></div></section>
  </div>;
}
