import type { Locale } from "@/i18n/config";

export const operationsCopy = {
  es: {
    eyebrow: "INGENIERÍA INDUSTRIAL × TI × INTELIGENCIA ARTIFICIAL",
    headline: ["Menos fricción.", "Más operación.", "Mejores sistemas."],
    intro: "Soy Jean Carrasco, ingeniero industrial y de software. Conecto procesos, datos y personas con tecnología e IA para que las operaciones funcionen mejor.",
    primary: "Exploremos tu operación", secondary: "Ver proyectos", available: "Abierto a proyectos y oportunidades",
    strip: ["Criterio industrial", "Integración de TI", "Automatización", "Agentes IA & LLMs"],
    system: "Arquitectura de una operación", demo: "MODELO INTERACTIVO", modes: ["Operaciones", "Atención", "Comercial"],
    source: "ENTRADAS", engine: "ORQUESTACIÓN", output: "RESULTADO", oversight: "Supervisión humana · Trazabilidad · KPIs",
    workflows: [
      { inputs: ["Inventario", "Pedidos", "Proveedores"], result: "Decisiones conectadas", nodes: ["Integrar datos", "Aplicar reglas", "Asistir con IA", "Medir y mejorar"], descriptions: ["Unificar la información de ventas, inventario y compras mediante APIs y bases de datos.", "Definir responsables, validaciones y alertas antes de automatizar el proceso.", "Usar LLMs para interpretar documentos y proponer acciones; las decisiones críticas pasan por una persona.", "Observar tiempos de ciclo, excepciones y calidad de datos para mejorar el flujo."] },
      { inputs: ["WhatsApp", "Documentos", "Consultas"], result: "Atención con contexto", nodes: ["Recibir consulta", "Recuperar contexto", "Preparar respuesta", "Resolver o escalar"], descriptions: ["Recibir mensajes en un flujo compartido, con contexto de la conversación.", "Consultar información autorizada mediante recuperación de conocimiento (RAG).", "Generar una respuesta basada en las fuentes disponibles, con límites claros.", "Derivar casos ambiguos a una persona y registrar el seguimiento."] },
      { inputs: ["Prospectos", "CRM", "Campañas"], result: "Seguimiento consistente", nodes: ["Unificar fuentes", "Validar información", "Priorizar prospectos", "Coordinar seguimiento"], descriptions: ["Conectar fuentes comerciales para reducir registros fragmentados y tareas repetidas.", "Enriquecer y depurar datos antes de incorporarlos al proceso comercial.", "Combinar criterios del negocio con IA para apoyar la clasificación de prospectos.", "Actualizar el CRM, asignar responsables y observar el avance del pipeline."] },
    ],
    aboutLabel: "01 / EL ENFOQUE", aboutTitle: "Entiendo la operación.\nConstruyo la solución.",
    aboutText: "He dirigido almacenes, cadenas de suministro y equipos de hasta 60 personas. Esa experiencia define cómo construyo tecnología: empiezo por el proceso, identifico la fricción y diseño un sistema que el equipo pueda usar, mantener y mejorar.",
    aboutNote: "Del piso de operación al software que lo conecta.", metrics: ["personas en equipos liderados", "almacenes bajo gestión operativa", "disciplinas conectadas: industria + software"],
    capabilitiesLabel: "02 / LO QUE RESUELVO", capabilitiesTitle: "Tecnología con\npropósito operativo.", capabilitiesIntro: "Cada integración empieza con una pregunta: ¿qué necesita funcionar mejor?",
    capabilities: [
      { title: "Operaciones que fluyen", text: "Mapeo procesos, identifico cuellos de botella y rediseño flujos de trabajo antes de automatizarlos.", tags: ["Mejora continua", "Lean", "Supply chain", "KPIs"], mark: "01" },
      { title: "Sistemas que conversan", text: "Conecto herramientas, bases de datos y APIs para que la información llegue a donde se necesita, sin trabajo duplicado.", tags: ["APIs", "Python / SQL", "Workflows", "Dashboards"], mark: "02" },
      { title: "IA que trabaja con tu equipo", text: "Integro agentes y LLMs con el conocimiento del negocio, controles humanos y seguimiento de calidad.", tags: ["Agentes IA", "LLMs", "RAG", "Automatización"], mark: "03" },
    ],
    workLabel: "03 / TRABAJO SELECCIONADO", workTitle: "Del problema\nal sistema.", workIntro: "Producto, automatización comercial y experiencia dirigiendo operaciones reales.", detail: "Explorar el enfoque", challenge: "El problema", approach: "La intervención", measurement: "Qué medir", visit: "Visitar QueryBay",
    cases: [
      { name: "QueryBay", category: "PRODUCTO / IA CONVERSACIONAL", title: "El conocimiento del negocio,\nen cada conversación.", text: "Agentes de IA conectados a canales de mensajería para apoyar la atención y la gestión de prospectos.", challenge: "Consultas repetidas y contexto repartido entre canales consumen tiempo del equipo.", approach: "Producto que conecta mensajería, modelos de lenguaje y flujos de atención. Mi rol combina producto, ingeniería e infraestructura.", measure: "Tiempo de primera respuesta, resolución y derivación a una persona.", tags: ["LLMs", "WhatsApp API", "Next.js", "Node.js"], type: "querybay" },
      { name: "Operaciones de datos", category: "DATOS / AUTOMATIZACIÓN COMERCIAL", title: "De fuentes dispersas\na un flujo comercial.", text: "Enriquecimiento de datos e integración de herramientas para coordinar prospección y seguimiento.", challenge: "La información comercial dispersa dificulta priorizar y dar seguimiento consistente.", approach: "Trabajo en generación de leads, enriquecimiento, infraestructura de correo y optimización de pipeline dentro de Janium.", measure: "Calidad del dato, tiempo de preparación y continuidad del seguimiento.", tags: ["Python", "APIs", "Data enrichment", "CRM"], type: "data" },
      { name: "Operación industrial", category: "OPERACIONES / SUPPLY CHAIN", title: "La perspectiva del terreno\ncambia la solución.", text: "Gestión de almacenes, inventario, mantenimiento e importaciones en Maderas América.", challenge: "Coordinar inventario, ventas y maquinaria exige visibilidad y responsabilidad compartida.", approach: "Dirección de la operación diaria de cinco almacenes. Esta experiencia es la base de mi enfoque de integración tecnológica.", measure: "Exactitud de inventario, disponibilidad y tiempos de atención.", tags: ["5 almacenes", "Inventario", "Mantenimiento", "Importaciones"], type: "industrial" },
    ],
    methodLabel: "04 / CÓMO TRABAJO", methodTitle: "Primero el proceso.\nDespués, la tecnología.", steps: [
      { title: "Entender", text: "Observar la operación, hablar con el equipo y establecer una línea base.", deliverable: "Mapa del proceso + prioridades" },
      { title: "Diseñar", text: "Definir el flujo, las integraciones y los criterios de éxito junto al negocio.", deliverable: "Arquitectura + alcance medible" },
      { title: "Implementar", text: "Construir un piloto, probar excepciones y preparar al equipo para usarlo.", deliverable: "Sistema integrado + documentación" },
      { title: "Mejorar", text: "Comparar con la línea base, revisar fallos y ajustar con datos de uso.", deliverable: "KPIs + mejora continua" },
    ],
    calculatorLabel: "EXPLORA UNA OPORTUNIDAD", calculatorTitle: "¿Cuánto tiempo hay\nen lo repetitivo?", calculatorText: "Ajusta los supuestos y estima el tiempo que podrías recuperar en un proceso. Un punto de partida para una conversación real.", volume: "Tareas por semana", minutes: "Minutos por tarea", automation: "Parte del tiempo que se automatizaría", recovered: "horas recuperables / mes", before: "Carga actual", after: "Carga restante", hours: "h / mes", caveat: "Estimación ilustrativa, no un resultado garantizado. Usa 4,33 semanas/mes; no incluye implementación, mantenimiento ni gestión de excepciones.", formula: "tareas × minutos ÷ 60 × 4,33 × % automatizable", calculatorCta: "Hablemos de este proceso",
    experienceLabel: "05 / TRAYECTORIA", experienceTitle: "Operaciones reales.\nPerspectiva integral.", education: "FORMACIÓN", languages: "IDIOMAS", now: "Actualidad",
    contactLabel: "EL SIGUIENTE PASO", contactTitle: "Tu operación puede\nfuncionar mejor.", contactText: "Cuéntame dónde se atasca el trabajo. Podemos empezar por un proceso, una integración o una oportunidad concreta para aplicar IA.", contactCta: "Conversemos", copy: "Copiar correo", copied: "Correo copiado", copyFailed: "No se pudo copiar. Puedes seleccionar el correo o abrir el enlace.", contactOptions: "Proyectos · Consultoría · Oportunidades profesionales", footer: "Ingeniería industrial. Tecnología aplicada. Mejora continua.", top: "Volver arriba",
  },
  en: {
    eyebrow: "INDUSTRIAL ENGINEERING × IT × ARTIFICIAL INTELLIGENCE",
    headline: ["Less friction.", "Better operations.", "Smarter systems."],
    intro: "I'm Jean Carrasco, an industrial and software engineer. I connect processes, data and people through technology and AI to make operations work better.",
    primary: "Let's explore your operation", secondary: "Explore my work", available: "Open to projects and opportunities",
    strip: ["Industrial thinking", "IT integration", "Automation", "AI agents & LLMs"],
    system: "An operation, connected", demo: "INTERACTIVE MODEL", modes: ["Operations", "Support", "Sales"],
    source: "INPUTS", engine: "ORCHESTRATION", output: "OUTCOME", oversight: "Human oversight · Traceability · KPIs",
    workflows: [
      { inputs: ["Inventory", "Orders", "Suppliers"], result: "Connected decisions", nodes: ["Integrate data", "Apply rules", "Assist with AI", "Measure & improve"], descriptions: ["Bring sales, inventory and purchasing information together through APIs and databases.", "Define ownership, validations and alerts before automating the process.", "Use LLMs to interpret documents and suggest actions; critical decisions stay with a person.", "Track cycle times, exceptions and data quality to improve the workflow."] },
      { inputs: ["WhatsApp", "Documents", "Questions"], result: "Context-aware support", nodes: ["Receive request", "Retrieve context", "Prepare response", "Resolve or escalate"], descriptions: ["Bring incoming messages into a shared workflow with conversation context.", "Retrieve authorized business knowledge using retrieval-augmented generation (RAG).", "Generate a response grounded in available sources, with clear boundaries.", "Route ambiguous cases to a person and record the follow-up."] },
      { inputs: ["Prospects", "CRM", "Campaigns"], result: "Consistent follow-up", nodes: ["Unify sources", "Validate information", "Prioritize prospects", "Coordinate follow-up"], descriptions: ["Connect commercial data sources to reduce fragmented records and repeated work.", "Enrich and clean information before it enters the sales workflow.", "Combine business criteria and AI to support prospect classification.", "Update the CRM, assign ownership and monitor pipeline progress."] },
    ],
    aboutLabel: "01 / THE PERSPECTIVE", aboutTitle: "I understand the operation.\nI build the solution.",
    aboutText: "I've managed warehouses, supply chains and teams of up to 60 people. That experience shapes how I build technology: understand the process, find the friction and design a system the team can use, maintain and improve.",
    aboutNote: "From the operations floor to the software that connects it.", metrics: ["people across teams led", "warehouses under operational management", "connected disciplines: industry + software"],
    capabilitiesLabel: "02 / WHAT I SOLVE", capabilitiesTitle: "Technology with\nan operational purpose.", capabilitiesIntro: "Every integration starts with a question: what needs to work better?",
    capabilities: [
      { title: "Operations that flow", text: "I map processes, identify bottlenecks and redesign workflows before automating them.", tags: ["Continuous improvement", "Lean", "Supply chain", "KPIs"], mark: "01" },
      { title: "Systems that communicate", text: "I connect tools, databases and APIs so information reaches the right place without duplicated work.", tags: ["APIs", "Python / SQL", "Workflows", "Dashboards"], mark: "02" },
      { title: "AI that works with your team", text: "I integrate agents and LLMs with business knowledge, human oversight and quality monitoring.", tags: ["AI agents", "LLMs", "RAG", "Automation"], mark: "03" },
    ],
    workLabel: "03 / SELECTED WORK", workTitle: "From the problem\nto the system.", workIntro: "Product engineering, sales automation and experience leading real operations.", detail: "Explore the approach", challenge: "The problem", approach: "The intervention", measurement: "What to measure", visit: "Visit QueryBay",
    cases: [
      { name: "QueryBay", category: "PRODUCT / CONVERSATIONAL AI", title: "Business knowledge,\nin every conversation.", text: "AI agents connected to messaging channels to support customer conversations and prospect management.", challenge: "Repeated questions and context scattered across channels take time away from the team.", approach: "A product connecting messaging, language models and support workflows. My role spans product, engineering and infrastructure.", measure: "First response time, resolution and handoff to a person.", tags: ["LLMs", "WhatsApp API", "Next.js", "Node.js"], type: "querybay" },
      { name: "Data operations", category: "DATA / SALES AUTOMATION", title: "From scattered sources\nto a sales workflow.", text: "Data enrichment and tool integration to coordinate prospecting and follow-up.", challenge: "Fragmented sales information makes prioritization and consistent follow-up difficult.", approach: "Work on lead generation, enrichment, email infrastructure and pipeline optimization at Janium.", measure: "Data quality, preparation time and follow-up continuity.", tags: ["Python", "APIs", "Data enrichment", "CRM"], type: "data" },
      { name: "Industrial operations", category: "OPERATIONS / SUPPLY CHAIN", title: "The view from the floor\nchanges the solution.", text: "Warehouse, inventory, maintenance and import management at Maderas América.", challenge: "Coordinating inventory, sales and machinery requires visibility and shared accountability.", approach: "Leading daily operations across five warehouses. This experience informs my approach to technology integration.", measure: "Inventory accuracy, availability and fulfillment times.", tags: ["5 warehouses", "Inventory", "Maintenance", "Imports"], type: "industrial" },
    ],
    methodLabel: "04 / HOW I WORK", methodTitle: "The process first.\nThen, the technology.", steps: [
      { title: "Understand", text: "Observe the operation, talk to the team and establish a baseline.", deliverable: "Process map + priorities" },
      { title: "Design", text: "Define the workflow, integrations and success criteria together with the business.", deliverable: "Architecture + measurable scope" },
      { title: "Implement", text: "Build a pilot, test exceptions and prepare the team to use it.", deliverable: "Integrated system + documentation" },
      { title: "Improve", text: "Compare against the baseline, review failures and adjust using real usage data.", deliverable: "KPIs + continuous improvement" },
    ],
    calculatorLabel: "EXPLORE AN OPPORTUNITY", calculatorTitle: "How much time goes\ninto repetitive work?", calculatorText: "Adjust the assumptions to estimate the time you could recover in a process. A starting point for a real conversation.", volume: "Tasks per week", minutes: "Minutes per task", automation: "Share of time that could be automated", recovered: "recoverable hours / month", before: "Current workload", after: "Remaining workload", hours: "h / month", caveat: "Illustrative estimate, not a guaranteed outcome. Uses 4.33 weeks/month; excludes implementation, maintenance and exception handling.", formula: "tasks × minutes ÷ 60 × 4.33 × automatable %", calculatorCta: "Let's discuss this process",
    experienceLabel: "05 / EXPERIENCE", experienceTitle: "Real operations.\nA broader perspective.", education: "EDUCATION", languages: "LANGUAGES", now: "Present",
    contactLabel: "THE NEXT STEP", contactTitle: "Your operation can\nwork better.", contactText: "Tell me where work gets stuck. We can start with one process, one integration or a concrete opportunity to apply AI.", contactCta: "Let's talk", copy: "Copy email", copied: "Email copied", copyFailed: "Couldn't copy. You can select the email or open its link.", contactOptions: "Projects · Consulting · Career opportunities", footer: "Industrial engineering. Applied technology. Continuous improvement.", top: "Back to top",
  },
};

export type OperationsCopy = (typeof operationsCopy)[Locale];
